runners:
  - name: "aws-runner"
    cloud: "aws"
    instance_type: "t2.nano"
    region: "us-east-2"
    machine_image: "ami-0cf0e376c672104d6"
    preemptible: false
    labels:
      - "cirun-aws-runner"
