runners:
  - name: "aws-runner"
    cloud: "aws"
    instance_type: "p3.2xlarge"
    region: "us-east-1"
    machine_image: "ami-053f492a130a35885"
    preemptible: false
    labels:
      - "cirun-aws-runner"
