# Self-Hosted Github Action Runners on GCP via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: "gpu-runner"
    # Cloud Provider: GCP
    cloud: "gcp"
    # Cheapest GPU on GCP
    gpu: "nvidia-tesla-t4"
    # Cheapest VM on GCP, with GPU attachable
    instance_type: "n1-standard-1"
    region: "us-central1-b"
    machine_image: "scikit-learn-custom-gpu:scikit-learn-custom-gpu"
    preemptible: false
    # Add this label in the "runs-on" param in .github/workflows/<workflow-name>.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-gpu-runner"
