# Self-Hosted Github Action Runners on GCP via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: "gpu-runner"
    cloud: "gcp"
    gpu: "nvidia-tesla-v100"
    instance_type: "n1-standard-4"
    machine_image: "third-campus-393023:scikit-learn-gpu-v3"
    region:
      - "us-east1-c"
      - "us-central1-a"
      - "us-central1-b"
      - "us-central1-c"
      - "us-central1-f"
      - "us-west1-a"
      - "us-west1-b"
    preemptible: false
    # Add this label in the "runs-on" param in .github/workflows/ci_run_trigger.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-gpu-runner"
