# Self-Hosted Github Action Runners on GCP via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: "gpu-runner"
    # Cloud Provider: GCP
    cloud: "gcp"
    # Cheapest GPU on GCP
    gpu: "nvidia-tesla-t4"
    # Cheapest VM on GCP, with GPU attachable
    instance_type: "n1-standard-2"
    machine_image: "third-campus-393023:scikit-learn-gpu-v3"
    region:
      - "us-central1-a"
      - "us-central1-b"
      - "us-central1-c"
      - "us-central1-f"
      - "us-east1-c"
      - "us-east1-d"
      - "us-east4-a"
      - "us-east4-b"
      - "us-east4-c"
      - "us-west1-a"
      - "us-west1-b"
      - "us-west2-b"
      - "us-west2-c"
      - "us-west3-b"
      - "us-west4-a"
      - "us-west4-b"
    preemptible: false
    # Add this label in the "runs-on" param in .github/workflows/ci_run_trigger.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-gpu-runner"
