runners:
  - name: "aws-runner"
    cloud: "aws"
    instance_type: "t2.nano"
    region: "eu-west-1"
    machine_image: "ami-0a18875dd14331c0a"
    preemptible: false
    labels:
      - "cirun-aws-runner"
