# make it explicit that we favor the new container-based travis workers
language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: xenial

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/sklearn
    - OMP_NUM_THREADS=2
    - OPENBLAS_NUM_THREADS=2
    - PYTEST_VERSION=latest

matrix:
  include:
    # Linux environment to test scikit-learn against numpy and scipy master
    # installed from their CI wheels in a virtualenv with the Python
    # interpreter provided by travis.
    - python: 3.7
      env:
        - CHECK_WARNINGS="true"
        - CI_CPU_COUNT="3"
      if: type = cron OR commit_message =~ /\[scipy-dev\]/

    # As above but build scikit-learn with Intel C compiler (ICC).
    - python: 3.7
      env:
        - CHECK_WARNING="true"
        - BUILD_WITH_ICC="true"
        - CI_CPU_COUNT="3"
      if: type = cron OR commit_message =~ /\[icc-build\]/

    - python: 3.7
      env:
        - CI_CPU_COUNT="8"
      os: linux
      arch: arm64
      if: type = cron OR commit_message =~ /\[arm64\]/
    - python: 3.7
      env:
        - CI_CPU_COUNT="8"
        - BUILD_WHEEL="true"
        - CIBW_TEST_REQUIRES="pytest pytest-xdist"
        - CIBW_TEST_COMMAND="pytest -n 8 --pyargs sklearn"
        - CIBW_BUILD_VERBOSITY="1"
      os: linux
      arch: arm64
      services: docker
      # if: commit_message =~ /\[cd\ build\]/

install:
  - if [ $BUILD_WHEEL == "true" ]; then
      python3 -m pip install cibuildwheel==1.6.4;
    else
      source build_tools/travis/install.sh;
    fi
script:
  - if [ $BUILD_WHEEL == "true" ]; then
      python3 -m cibuildwheel --output-dir wheelhouse;
    else
      bash build_tools/travis/test_script.sh || travis_terminate 1;
      bash build_tools/travis/test_docs.sh || travis_terminate 1;
      bash build_tools/travis/test_pytest_soft_dependency.sh || travis_terminate 1;
    fi
after_success:
    - if [ $BUILD_WHEEL != "true" ]; then
        source build_tools/travis/after_success.sh
      fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
