[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools<60.0",
    "wheel",
    "Cython>=0.29.24",

    # use oldest-supported-numpy which provides the oldest numpy version with
    # wheels on PyPI
    #
    # see: https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg
    "oldest-supported-numpy",

    "scipy>=1.3.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "scikit-learn"
description = "A set of python modules for machine learning and data mining"
readme = "README.rst"
license = {text = "BSD 3-Clause License"}
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: C",
    "Programming Language :: Python",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
maintainers = [
    {name = "Andreas Mueller", email = "amueller@ais.uni-bonn.de"},
]
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.19.2; platform_python_implementation=='PyPy'",
    "numpy>=1.17.3; platform_python_implementation!='PyPy'",
    "scipy>=1.3.2",
    "threadpoolctl>=2.0.0",
    "joblib>=1.0.0",
]

dynamic = ["version"]

[project.urls]
"Bug Tracker" = "https://github.com/scikit-learn/scikit-learn/issues"
Documentation = "https://scikit-learn.org/stable/documentation.html"
"Source Code" = "https://github.com/scikit-learn/scikit-learn"

[project.optional-dependencies]
tests = [
    "matplotlib>=3.1.2",
    "scikit-image>=0.16.2",
    "pandas>=1.0.5",
    "pytest>=5.0.1",
    "pytest-cov>=2.9.0",
    "flake8>=3.8.2",
    "black>=22.3.0",
    "mypy>=0.961",
    "pyamg>=4.0.0",
    "numpydoc>=1.2.0",
]
docs = [
    "matplotlib>=3.1.2",
    "scikit-image>=0.16.2",
    "pandas>=1.0.5",
    "seaborn>=0.9.0",
    "memory_profiler>=0.57.0",
    "sphinx>=4.0.1",
    "sphinx-gallery>=0.7.0",
    "numpydoc>=1.2.0",
    "Pillow>=7.1.2",
    "sphinx-prompt>=1.3.0",
    "sphinxext-opengraph>=0.4.2",
]

[tool.black]
line-length = 88
target_version = ['py38', 'py39', 'py310']
preview = true
exclude = '''
/(
    \.eggs         # exclude a few common directories in the
  | \.git          # root of the project
  | \.mypy_cache
  | \.vscode
  | build
  | dist
  | doc/tutorial
  | doc/_build
  | doc/auto_examples
  | sklearn/externals
  | asv_benchmarks/env
)/
'''
