# Unit test for ARM
name: Unit test for ARM
permissions:
  contents: read

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    # needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: build_tools/cirrus/pymin_conda_forge_linux-aarch64_conda.lock
          environment-name: ci

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install linters
  #       run: |
  #         source build_tools/shared.sh
  #         # Include pytest compatibility with mypy
  #         pip install pytest $(get_dep ruff min) $(get_dep mypy min) $(get_dep black min) cython-lint
  #     - name: Run linters
  #       run: ./build_tools/linting.sh
