# Unit test for ARM
name: Unit test for ARM
permissions:
  contents: read

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install linters
        run: |
          source build_tools/shared.sh
          # Include pytest compatibility with mypy
          pip install pytest $(get_dep ruff min) $(get_dep mypy min) $(get_dep black min) cython-lint
      - name: Run linters
        run: ./build_tools/linting.sh


  # run-unit-tests:
  #   name: Run unit tests
  #   needs: [lint]
  # steps:
  #   - name:
