name: Build Arm Wheels

on: [push]

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Start arm service
        run: |
          docker run --rm --name arm-docker --privileged -d arm64v8/ubuntu sleep 100000
      - name: Install docker client
        run: |
          docker exec -u root arm-docker apt-get update
          docker exec -u root arm-docker apt-get install curl -y

      - name: Stop arm container
        run: docker stop arm-docker
        if: ${{ always() }}
