name: Build Arm Wheels

on: [push]

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Start arm service
        run: |
          docker run --rm --name arm-docker --privileged -d -p 2375:2375 arm64v8/ubuntu sleep 100000
      - name: Install docker client
        run: |
          set -ex
          RUN="docker exec -u root arm-docker"
          $RUN apt-get update
          $RUN apt-get install curl sudo -y
          $RUN curl -fsSL https://download.docker.com/linux/static/stable/aarch64/docker-19.03.13.tgz -o docker-19.03.13.tgz
          $RUN tar xzvf docker-19.03.13.tgz
          $RUN find docker -type f -exec cp {} /usr/bin \;
          docker exec -d -u root arm-docker sudo dockerd -H tcp://0.0.0.0:2375 &
          $RUN docker version

      - name: Check docker client from host machine
        run:
          docker version
        env:
          DOCKER_HOST: tcp://0.0.0.0:2375

      - name: Stop arm container
        run: docker stop arm-docker
        if: ${{ always() }}
