name: Build Arm Wheels

on: [push]

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Start arm64 service
        run: docker run -it --privileged --name arm-docker -d -p 2375:2375 arm64v8/docker:dind
      - name: Check arm64
        run: |
          docker version
        env:
          DOCKER_HOST: tcp://127.0.0.1:2375
      - name: Stop arm-container
        run: docker stop arm-docker
        if: ${{ always() }}
