name: Build Arm Wheels

on: [push]

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.0.1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Check arm64
        run: |
          set -xe
          docker info
          docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock amd64/docker:dind docker info
