name: "Check Manifest"

on: [push]

jobs:
  check-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        # scipy and cython are required to build sdist
        run: |
          python -m pip install --upgrade pip
          pip install check-manifest scipy cython
      - run: |
          check-manifest -v

  update-tracker:
    uses: ./.github/workflows/update_tracking_issue.yml
    if: ${{ always() }}
    needs: [check-manifest]
    with:
      job_status: ${{ needs.check-manifest.status }}
    secrets:
      BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
