name: CIRun Trigger

on:
  pull_request_target:
    types: [labeled]
  push:
    branches:
      - "main"
      - "cirun_gcp"

jobs:
  # build:
  #   runs-on: ubuntu-22.04
  #   if: ${{ github.event_name == 'pull_request' && github.event.label.name == 'gpu' }}
  #   steps:
  #     - name: Remove label
  #       uses: actions/github-script@v6
  #       with:
  #         script: |
  #           github.rest.issues.removeLabel({
  #             owner: context.issue.owner,
  #             repo: context.repo.repo,
  #             issue_number: context.issue.number,
  #             name: 'gpu'
  #           })
  # - uses: actions/checkout@v3
  # - name: Build wheel
  #   uses: pypa/cibuildwheel@v2.14.1
  #   env:
  #     CIBW_BUILD: cp311-manylinux_x86_64
  #     CIBW_BUILD_VERBOSITY: 1
  #     CIBW_ENVIRONMENT: SKLEARN_BUILD_PARALLEL=3

  # - uses: actions/upload-artifact@v3
  #   with:
  #     name: wheelhouse
  #     path: ./wheelhouse/*.whl

  test:
    runs-on: "cirun-gpu-runner--${{ github.run_id }}"
    defaults:
      run:
        shell: bash -el {0}
    # if: ${{ github.event.label.name == 'gpu' }}
    # needs: [build]
    steps:
      - name: Check nvidia
        run: |
          nvidia-smi

      - name: Install dependencies
        run: |
          conda activate base
          python -m pip install array_api_compat cupy-cuda11x pytest

      - name: Install scikit-learn nightly
        run: |
          conda activate base
          python -m pip uninstall -y scikit-learn
          python -m pip install --pre --extra-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple scikit-learn

      - name: Run tests
        run: |
          python -m pytest --color=yes --pyargs sklearn -k array_api
