name: CIRun Trigger

on:
  pull_request_target:
    types: [labeled]
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.label.name == 'gpu' }}
    steps:
      - name: Remove label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.issue.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'gpu'
            })
      # - uses: actions/checkout@v3
      # - name: Build wheel
      #   uses: pypa/cibuildwheel@v2.14.1
      #   env:
      #     CIBW_BUILD: cp311-manylinux_x86_64
      #     CIBW_BUILD_VERBOSITY: 1
      #     CIBW_ENVIRONMENT: SKLEARN_BUILD_PARALLEL=3

      - name: Create file
        run: |
          mkdir wheelhouse
          echo "This is cool" > wheelhouse/hello.txt

      - uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: ./wheelhouse/*.txt

  test:
    runs-on: "cirun-aws-runner--${{ github.run_id }}"
    needs: [build]
    steps:
      - name: Download wheel
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse
          path: wheelhouse

      - name: Check cwd
        run: ls wheelhouse
