name: CIRun GPU

on:
  push:
    branches:
      - main
      - cirun_gpu
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+.X"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # - name: Build wheels
      # uses: pypa/cibuildwheel@v2.14.1
      # env:
      #   CIBW_BUILD: cp311-manylinux_x86_64
      #   CIBW_BUILD_VERBOSITY: 1

      - name: Create file
        run: |
          mkdir wheelhouse
          echo "This is cool" > wheelhouse/hello.txt

      - uses: actions/upload-artifact@v3
        with:
          name: wheelhouse
          path: ./wheelhouse/*.txt

  test:
    runs-on: "cirun-aws-runner--${{ github.run_id }}"
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Download wheel
        uses: actions/download-artifact@v3
        with:
          name: wheelhouse
          path: wheelhouse

      - name: Check cwd
        run: ls -R

      # - name: Install PyTorch, CuPy
      # - name: Install dependencies and scikit-learn
      # - name: Run tests
