name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened]

# Restrict the permissions granted to the use of secrets.GITHUB_TOKEN in this
# github actions workflow:
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: thomasjpfan/labeler@3d528cd5d18871d09b85ac5d9fb1addf7b68753f
      continue-on-error: true
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        max-labels: "3"
        configuration-path: ".github/labeler-module.yml"

  triage_file_extensions:
    runs-on: ubuntu-latest
    steps:
    - uses: thomasjpfan/labeler@3d528cd5d18871d09b85ac5d9fb1addf7b68753f
      continue-on-error: true
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/labeler-file-extensions.yml"
